$:
  push:
    - services:
        - docker
      imports: https://cnb.cool/jaguarliu.cool/dify-tool/keys/-/blob/main/git_token.yml
      docker:
        build: .ide/Dockerfile
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/jaguarliuu/rookie_text2data.git
            auth_type: https
            username: $GIT_USERNAME
            password: $EUMENIDES_TOKEN
            branch: $CNB_BRANCH